/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class slotLogic */

#ifndef _Included_slotLogic
#define _Included_slotLogic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     slotLogic
 * Method:    loadAssets
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_slotLogic_loadAssets
  (JNIEnv *, jobject);

/*
 * Class:     slotLogic
 * Method:    getBalance
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_slotLogic_getBalance
  (JNIEnv *, jobject);

/*
 * Class:     slotLogic
 * Method:    getCurrentBet
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_slotLogic_getCurrentBet
  (JNIEnv *, jobject);

/*
 * Class:     slotLogic
 * Method:    nextBet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_slotLogic_nextBet
  (JNIEnv *, jobject);

/*
 * Class:     slotLogic
 * Method:    spin
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_slotLogic_spin
  (JNIEnv *, jobject);

/*
 * Class:     slotLogic
 * Method:    getLastBoard
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_slotLogic_getLastBoard
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
