/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class window */

#ifndef _Included_window
#define _Included_window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     window
 * Method:    calculateWinnings
 * Signature: ([[ID)D
 */
JNIEXPORT jdouble JNICALL Java_window_calculateWinnings
  (JNIEnv *, jobject, jobjectArray, jdouble);

/*
 * Class:     window
 * Method:    loadAssets
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_window_loadAssets
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
